name: Run index.js every 10 minutes

on:
  push:  # Trigger on every push
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  

      - name: Install dependencies
        run: |
          npm install  # Install your project's dependencies
          npx playwright install  # Install Playwright
        shell: bash  # Use 'bash' as the shell

      - name: Run index.js
        run: node index.js  # Execute the index.js file
