name: Run index.js every 1 day

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          

      - name: Install dependencies
        run: |
          npm install  # Install your project's dependencies
          npx playwright install  # Install Playwright
        shell: bash  # Use 'bash' as the shell

      - name: Run index.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          HEADLESS: ${{ secrets.HEADLESS }}
        run: node index.js